### ISSUE TITLE
Add Hex Five JEDEC ID to riscv/riscv-openocd

### ISSUE THREAD

**Issue by cgarlati** [hex-five/multizone-fpga#6]
Request addition of Hex Five's JEDEC ID to https://github.com/riscv/riscv-openocd/blob/5d9f48640461fbac5c30958f63a01e666ee64dd4/src/helper/jep106.inc

**Comment by cgarlati** [comment]
@borancar  Any  progress?

**Comment by borancar** [comment]
We're in the June version, I'll trigger the OpenOCD flow now.

**Comment by borancar** [comment]
Patch sent to openocd mainline - http://openocd.zylin.com/#/c/5244/, waiting for merge before sending a PR to SiFive.
