### ISSUE TITLE
Update "Requirements" section in README

### ISSUE THREAD

**Issue by AntonHermann** [hex-five/multizone-fpga#8]
Hey :)
when I tried building the project, some strange Java errors occured, like "class String" not found and so on.

Only when I looked um the original [sifive/freedom](https://github.com/sifive/freedom) repository to find out where to submit my issue I noticed that in the original repo the README is much more detailed, with requirements like Scala, sbt, etc.

In the end my initial error was fixed in a second by installing Scala.

It would be great if you could either reference that there are more requirements to be found in the sifive repo or if you could copy their instructions, so that others can find the relevant information more easily.

Thanks and best wishes

**Comment by cgarlati** [comment]
Done. Thank you Anton for the sugestion.

Thanks!
